### PR TITLE
Fix init warning in xCode 7

### PR DESCRIPTION
**Pull request by ClioMobile**

### CODE REVIEW

**Comment by pixelglow** [comment]
Thanks for the pull request!

I would prefer the `- (instancetype)init NS_UNAVAILABLE;` moved to the `.h` files and any `init` implementation dropped from the `.m` files, similar to [this example](http://craftbeercraftcode.com/2014/12/28/better-brewing-with-ns_unavailable/). The implementation will never be called in any case, and at least library clients will get a compile-time error.

I haven't yet tested ZipZap on Xcode 7, so I don't know if my preference would fix the init warning as well. Do try it out and let us know, then rebase this to a single commit and I'll merge it down.

**Comment by ClioMobile** [comment]
There you go

**Comment by pixelglow** [comment]
Thanks for updating the headers.

If you drop the implementation of `init` entirely, i.e. in the `*.m` files:

    -(instancetype) init
     {
	    [self doesNotRecognizeSelector:_cmd];
 	    return nil;
     }

... do you still get some sort of warning on building? If you don't get any warnings, please drop the implementation of `init`.

Also, please rebase to a single commit e.g.

    git rebase -i HEAD~3 # if you have 3 commits
    # change the 2 later commits from "pick" to "squash"
    git push --force

See http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html for a detailed explanation.

**Comment by ClioMobile** [comment]
Yes, the implementation of the init method is definitely required to dismiss the warning, here is how the NSObject header defines `init` in iOS 9:

```
- (instancetype)init
#if NS_ENFORCE_NSOBJECT_DESIGNATED_INITIALIZER
    NS_DESIGNATED_INITIALIZER
#endif
    ;
```
and 

```
/* NS_ENFORCE_NSOBJECT_DESIGNATED_INITIALIZER == 1 
 * marks -[NSObject init] as a designated initializer. */
#if !defined(NS_ENFORCE_NSOBJECT_DESIGNATED_INITIALIZER)
#   define NS_ENFORCE_NSOBJECT_DESIGNATED_INITIALIZER 1
#endif
```

Didn't know you could squash commits, thx

**Comment by pixelglow** [comment]
OK, I've taken a more detailed look and also played around a little with Xcode 7. Please make the following changes and rebase to a single commit:

* The `init` implementations should `@throw [NSException exceptionWithName:NSGenericException reason:@"*** -[??? init]: should never be used" userInfo:nil];` (substitute the class name for ???)
   * This is what `[[NSNotification alloc] init]` does on Mac OS X 10.11. Other such classes seem to return either `nil` or proceed, which seems like a mistake.
   * `doesNotRecognizeSelector:` is not appropriate since you also have to override `respondsToSelector:` to keep the contract intact, and we end up with subtle inconsistencies with the Objective-C runtime functions.

* Move `ZZArchive.mm:27` to the header file. I know this makes it public but we should tell clients that they can't use `init` by itself on an archive. I'll bump the minor version in due course.

**Comment by pixelglow** [comment]
@ClioMobile any progress on these changes?

**Comment by pixelglow** [comment]
Superseded by @a05281e.

**Pull request closed without merging**
