### PR TITLE
uncodedFileName as NSData *

### PR DESCRIPTION
**Pull request by Doxxer**
See issue #119

### CODE REVIEW

**Comment by pixelglow** [comment]
Thanks for the pull request, good concept.

*Definite fixes before merging*

* Use `rawFileName` instead of `uncodedFileName`. I tend to prefer short, Germanic phrases where possible instead of longer/complex Latinate phrases.

* `git rebase -i` all your commits to a single commit.

*Optional fixes*

* Provide a `fileNameWithEncoding:` method that returns a filename with a particular encoding. Then refactor `fileName` to use this, possibly dropping the private `stringWithBytes` method.

* Drop the string encoding key at the `ZZArchive` level. As you've said in #119, sometimes the filenames have different encodings and we shouldn't enforce this at the archive level. It's confusing then to have 3 or 4 different, interacting ways of determine encoding -- best just to stick to explicit encoding if necessary at the method level, and implicitly using the UTF-8 flag or defaulting back to the spec CP437. See [my StackOverflow question](http://stackoverflow.com/questions/13261347/correctly-decoding-zip-entry-file-names-cp437-utf-8-or) for context.

Feel free to only implement the definites. We can discuss the optionals or I can do them myself.

**Comment by pixelglow** [comment]
Thanks for the update. Please rebase this branch to a single commit e.g. `git rebase -i HEAD~2` then `squash` ca7b6bb, then `git push --force` to update. Then I'll merge it down.

**Comment by Doxxer** [comment]
Done

**Comment by pixelglow** [comment]
Excellent.

**Pull request merged**
