### PR TITLE
Add syntax highlighting for code examples in Readme

### PR DESCRIPTION
**Pull request by vkotovv**
We can use github markdown features

### CODE REVIEW

**Comment by vkotovv** [comment]
@pixelglow Done, can be merged now!

**Comment by pixelglow** [comment]
One more thing before I merge, please rebase the two commits to a single commit. I generally prefer "atomic" commits.

**Comment by vkotovv** [comment]
I'm done with squashing.

**Comment by pixelglow** [comment]
Excellent! I'll merge it down now.

**Pull request merged**
